import { Interventions } from "@/components/views/Interventions";
import Head from "next/head";

export default function InterventionsPage() {
  return (
    <>
      <Head>
        <title>Nos interventions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Interventions />
    </>
  );
}
